// 容器组件(一般用于做布局)
  /*
  组件名(){}
  * 组件换行.属性(值)
  * .width()默认单位vp
  * .height()默认单位vp
  * .backgroundColor()色值，常为十六进制或内置色
   */
// 内容组件(一般用于做内容)
  /*
  组件名()
   */
// Column(){
// // 练习一
//   Text("文本1")
//   Text("文本2")
//   Text("文本3")
//   // 练习二
//   Row(){
//     Text("文本4")
//     Text("文本5")
//     Text("文本6")
//   }
// }
//   内置组件学习区：
//   Column(){
//     Text("LAFFEY_GOSLINNG")
//     // color E => Enum枚举
//       .backgroundColor(Color.Orange)
//       .width(150)
//       .height(50)
//     Row(){}
//       // 满屏尺寸默认为 360 vp
//       .width(150)
//       .height(50)
//       .background('#ff6600')
//   }
// Text("大壮")
//   .fontSize(35)
//   .fontColor(Color.Red)
//   .fontWeight(800)
/*文字组件美化效果作业
    Column(){
      Text("在千年桐寨，感受乡村全面振兴的力量")
        .fontSize(18)
        .width(320)
      Text("新华社新闻")
        .fontSize(14)
        .fontColor(Color.Gray)
        .width(320)
      Text("桂豫持续扩大对象开发")
        .fontSize(18)
        .width(320)
      Text("央视新闻")
        .fontSize(14)
        .fontColor(Color.Gray)
        .width(320)
    }
 ——————————————————————————————————————————————————
 当前进度为14/47
 */
@Entry
@Component
struct Index {
  build() {

    
  }
}